Fix fatal Error when npm.commands.info returns empty object
This pull request fixes the following error:
```
Fatal error: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at C:\Users\Felicien\git\TweakStyle\node_modules\grunt-version-check\tasks\version-check-grunt.js:72:46
    at C:\Users\Felicien\git\TweakStyle\node_modules\npm\lib\view.js:144:28
    at saved (C:\Users\Felicien\git\TweakStyle\node_modules\npm\lib\cache\caching-client.js:173:7)
    at C:\Users\Felicien\git\TweakStyle\node_modules\bower\node_modules\bower-json\node_modules\graceful-fs\polyfills.js:133:7
    at C:\Users\Felicien\git\TweakStyle\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
    at FSReqWrap.oncomplete (fs.js:82:15)
```

It happened when npm.commands.info returns null or empty data.
I got this error with `npm 3.3.6` and `electron-prebuilt` dependency.
It may be due to the last published version number (0.34.4) is lower than my current version (0.35.1).

With this fix, here the output of `grunt versioncheck` :
```
Running "versioncheck" task
>> electron-prebuilt (npm) is out of date. Your version: 0.35.1 latest: undefined
```

not perfect but at least it don't crash and it tells there is a newly published version.